# Generated by Django 4.2.11 on 2025-03-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_bio_user_profile_picture_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='created_at',
        ),
    ]
